ref_seq="AGCTGACTATCGTACTGATCTAGCTATGCTGACTGCTGATCGATGCTGTGATGCTATCGATGCTAGTCGATCGTACTGATCGTAGCTGATCGTAGCTATCGATGCTAGCTAGCTGCTAGTCGATCGAGTCTAGCTAGTCATGTCGACACTAGCTAGCTAGC"

base=["A","T","G","C"]

d1={}
for b1 in base:
	for b2 in base:
		b=b1+b2
		count_di=ref_seq.count(b)
		if(count_di>0):
			d1[b]=count_di


print(d1)
