ref_seq="ATCTGATGATCGTGATGTCATTGCTACGTGCTAGCTCGTATTGCAGTGCTAGCGAATTGCTGATCGGTAGCATTGCTGACTGCGCATTGCTGACTTCGTAATTGCTAGCTGCATTGCTAGCTGACTCGATTGC"

intron1=ref_seq[:25]

exons=ref_seq[25:60]

introns2=ref_seq[60:]

print(intron1+exons.lower()+introns2)
