s1="this is python programming"

#split

print(s1.split(" "))


s2="TACGCG TGACTGCT TGACTGCT TAGCTGC TAGTGCTCTAGT"
print(s2.split(" "))


seq="""AGCTAGCTGCT TAGCTGATGCT TAGCTGACTTATGCT TAGCTCAGTAGCTGACG TAGCTGCTGACGATGC
TGATCGTCTAGTCGT ATGCTGCAGCATGCT TACGTCGTAGTAGCTG AGCTTAGTATGCTAGC AGCTTGATGAC
GACTGATTGCTGCAGTCGTAG TACGTAGGACGATCGTGCATGC TGACTGTTAGCTATCG TGAGCTCACGCTAGGAT
ATGCTCATGCTGTCAGTC ACGTAGCTTCGAGT TAGCTGATGTGACTGACG TAGCTGTGTAGTCG TAGTCGGATC"""



print(seq.replace(" ","")) 



string="       python          "
print(string)

x=string.strip()
print(x)
