seq="TAGCTGTAGCGTCGAGCTAGCGATCTAGCGATCTACTGCTAGTCGTACGAGCTAGCTAGTCGATGCTGACTGATCGCTGATGTAGCATGTAGCTAGCTAGCTATGCTATCGTAGCTACGTAGCTAGCTGTACGAGCTGATGCGATGCGTAGGCTGCTATCACTAGCTAGCGTCATCGATCGTAGCTGTACGTAG"
#    0123456789..................................................................index in python (position nums)


print(seq)

#to access the characters by using position numbers
print(seq[4])

print(seq[56])

#to access the range of characters.
print(seq[2:10])


print(seq[30:78])

#count of A,T,G,C
print("count of A",seq.count("A"))

print("count of C", seq.count("C"))

print("count of G", seq.count("G"))

print("count of T", seq.count("T"))

#length

print(len(seq))

#replace T by U
print(seq.replace("T","U"))

#GC content

cG=seq.count("G")	#cG variable we will store the count of G
cC=seq.count("C")	#cC variable we will store the count of C

GC=((cG+cC)/len(seq))*100
print("GC content is",GC)

AT=(100-GC)

print("AT content", AT)

print(GC+AT)


#multiline sequence.
m="""TAGTGTCGTGCTAGTCGTAGTGAGCTGATGCTAGCTGGATCTAGCTGATCGTAGCTGATCGTAGCTGATCGTAGCTGTAGCTAGCTAGCTAGCTGCTGCATGCTAGCTGATGCATGCTAGCTGATCGTGCTAGCTGCTAGCTGACTGATCGCGATCGTAGCTGACATCTCGTGACTAC
GACTGTGCTAGCGAGCGAGCTGATGCTAGCTTACTGCTGATGCTGATCGTGATCGTGATGCTGTGCATGCTGATGCTAGTCGTAGCTGTAGCTGACGGCATGCTGATCGTAGCTAGCTGATGCTATCGATGCTAGCTAGTCGTAGCGCATGTCGTAGCATATGCTAGCACGTAGCTGATGCT
TAGCTTAGCATCGGATCGTAGCTCGGATGCGTATGCGTAGCTGATGCTGTACGATGCATGCTAGTCGTACGTACGTAGCTAGCTGACTGCTAGCTGAGCTAGCTGCTAGTGATGTCGTACGGCTGATGCGTACGTCATGGCAGCTAGTCGATGCTAGCTGATGCTACTATAGTCGAATGCTAGC
TGACTGACGTAGCGATGCTGATCGATGCTGATCGTAGCTGATGCTGATCGTAGCTGATCTAGTCGTAGCTGCTGATGCTAGTCGATGCTAGCGTGCTACGAGCTGACGTACGTGCTAGCTAGTCACGATGCTAGCTGACTGATCGCTAGACGTAGCTAGCTGTAGGTCGTAGCTAGCTGCTG
GATCGTACGTGACTGCATCGTAGCTGACTGCTGACTGATCGTGCATGACTACTGCTAGCTGATCGATCGTAGTCTGTAGCTGATCGATGCTAGCTAGCTGATCGTAGCTGACTAGCTAGCTAGCTAGCTAGCTAGCTGACTGACTGTAGCTGATCGACTGATGCGTATCGGTACGTGCATTCA
TATCTAGTGTAGTGATCGTAGTCGTGATCGATGCTGATCGTAGCTGATGCTGATCGATGCTGACTGATGTAGTCGTCGATGCATGCTAGCTGCTGACTGATGCTAGTCGTAGCTGCATCGTACGTAGCTAGCTAGCTAGCTAGCTAGTCGTAGCTGTGACTGTAGCGACTGATCGATGC"""

print(m)

print("count of A", m.count("A"))

print("count of C", m.count("C"))

print("count of G", m.count("G"))

print("count of T", m.count("T"))


#GC content

cG=m.count("G")	#cG variable we will store the count of G
cC=m.count("C")	#cC variable we will store the count of C

GC=((cG+cC)/len(m))*100
print("GC content is",GC)

AT=(100-GC)

print("AT content", AT)

print(GC+AT)

#lower()
print(m.lower())

#upper()
print(m.upper())


print(m[50])















 
