dna="""ATGCTGATCGTAGCTGATGCGTAGTCGATGTGTACTAGATTGCCTGATGATTGCATTGCCAGCTGATCGTACTGACGTACGTGTCGTATGCTAGTCGTAGCTGATCGTGCTGATCGTAGCTGATGCTAGTCGATCGT
TGATGCTGATCGTAGCTATTGCGACTGATCGTAGCGAATTGCTCGTAGCTGATGCTAGCTATATTGCCTAGCTATGCTGCTATCTAGCTATGCTAGCTAGCTGATCATCGTACTTGCTCGTAGCTAGCAGCTGCATTGCTAGCTCGTAGC
TGATCATTGCGTAGCTGTAGTGCTAGATTGCTCGAATTGCTACTGATGCTGATCGTAGCTATCGTAGCTGATGCTATTGCGATGTACATTGCTGATCGTAGGTAGCTGATGCGATCGCGATATTGCTGATCGTGTAGTCGATGCTAGTCGATGCTAGC
TGATCTGCTGATGTATTGCCTAGCTGATCGTAGCTAGATTGCTCGATCTGCGATATTGCGTGTGGTGTGTTGTGTTATTGCATTGCAGCTATTGCGATGCTGATCGTAGCTGATCATTGCTAGCTGCTGTAGTGATCGTAGCTGATTGCATGCTATTGC
TGATCGTACTGCTGACTGCATTGC"""

mot="ATTGC"

if mot in dna:
    count_mot=dna.count(mot)
    print("count of mot", count_mot)
else:
    print("Not found")

print("------------------------------------------------------------------------------------")

c_mot= "ATTGC"

for i in dna:
    Num_mot=dna.count(c_mot)
print("count of Num_mot", Num_mot)





