from Bio.Seq import Seq
s1=Seq("ATGCGATTAGACTAGCCGTAGTGTTAGTTACCGATCCGTTAGCCTGACGTACTGAATTGCCAACYGACCTGACTCATCGGACGAATGCTGACGTAGCTGATCGTGATGCCTGATGCTAAGTCGTAGCTGACGAT")

print(s1.complement())

print(s1.translate())

print(s1.reverse_complement())
